name: Environment
on: workflow_dispatch
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: main
    steps:
      - run: echo "${BRANCH_NAME}"
      - uses: actions/checkout@v4
        with :
          ref: ${{ env.BRANCH_NAME }}