name: Sequential Jobs
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest 
    steps:
      - run: sleep 10 && echo "Job 1 completed"
  second_job:
    runs-on: ubuntu-latest
    needs: first_job
    steps:
      - run: sleep 10 && echo "Job 2 completed"
  third_job:
    runs-on: ubuntu-latest
    needs: second_job
    steps:
      - run: sleep 10 && echo "Job 3 completed"